apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: integrationrunners.integrations.jupiterone.io
spec:
  group: integrations.jupiterone.io
  names:
    kind: IntegrationRunner
    listKind: IntegrationRunnerList
    plural: integrationrunners
    singular: integrationrunner
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: State of the runner
      jsonPath: .status.state
      name: State
      type: string
    - description: Detailed state message
      jsonPath: .status.stateDetail
      name: Detail
      type: string
    - description: Registration status of the runner
      jsonPath: .status.registration
      name: Registration
      type: string
    - description: Time since creation
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: IntegrationRunner is the Schema for the integrationrunners API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: IntegrationRunnerSpec defines the desired state of IntegrationRunner.
            properties:
              accountId:
                description: AccountID is the JupiterOne account ID that this integration
                  runner belongs to.
                type: string
              collectorId:
                description: CollectorID is the ID of the collector that this integration
                  runner is associated with.
                type: string
              collectorPoolId:
                description: CollectorPoolID is the ID of the pool that the collector
                  belongs to.
                type: string
              jupiterOneEnvironment:
                description: |-
                  JupiterOneEnvironment is the environment of the JupiterOne API that the integration runner will connect to.
                  This defaults to `us` if not specified.
                type: string
              secretAPITokenName:
                description: SecretAPITokenName is the name of the Kubernetes secret
                  that contains the user's API token for API access.
                type: string
              secretName:
                description: |-
                  SecretName is the name of the Kubernetes secret that contains the credentials for the integration runner.
                  This includes the registration token and the currently rotated token. The values in this secret change over time.
                type: string
              syncIntervalSeconds:
                description: SyncIntervalSeconds is the interval in seconds at which
                  the integration runner should sync data.
                type: integer
            type: object
          status:
            description: IntegrationRunnerStatus defines the observed state of IntegrationRunner.
            properties:
              lastHeartbeatTime:
                format: date-time
                type: string
              lastSyncTime:
                format: date-time
                type: string
              registration:
                type: string
              state:
                type: string
              stateDetail:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
