# The name of the collector (a.k.a IntegrationRunner) in the same namespace
collectorName: runner

# Load Kubernetes configuration from the default location
loadKubernetesConfigFromDefault: false

# Namespaces to ingest instead of all namespaces
# includeNamespaces:
#   - default
#   - jupiterone

# Namespaces to exclude from ingestion
# excludeNamespaces: []

# Polling interval defines how often the integration should run. Options are:
# DISABLED
# THIRTY_MINUTES
# ONE_HOUR
# FOUR_HOURS
# EIGHT_HOURS
# TWELVE_HOURS
# ONE_DAY
# ONE_WEEK
pollingInterval: "ONE_WEEK"

# Polling interval cron schedule (instead of pollingInterval)
# pollingIntervalCron:
#   hour: 2          # Hour of the day (0-23)
#   dayOfWeek: 0    # Day of the week (0-6,

# Resource Group ID to associate with the integration instance
# resourceGroupId: "your-resource-group-id"

# CRD Mapping Configuration to customize how CRDs are ingested
# Can be set via --set-file crdMappingConfig=path/to/file.yaml
# The following is an example configuration.
# crdMappingConfig: |
#  resources:
#    - name: integrationrunners.integrations.jupiterone.io
#      version: v1
#      _type: kube_cr_integration_runner
#      _class: Process
#      propertyToFieldMap:
#        _key: metadata.uid
#        name: metadata.name
#        namespace: metadata.namespace
#        createdOn: metadata.creationTimestamp
#        accountId: spec.accountId
#        collectorId: spec.collectorId
#        collectorPoolId: spec.collectorPoolId
#        jupiterOneEnvironment: spec.jupiterOneEnvironment
#        secretAPITokenName: spec.secretAPITokenName
#        secretName: spec.secretName
#        syncIntervalSeconds: spec.syncIntervalSeconds
#
#    - name: integrationinstancejobs.integrations.jupiterone.io
#      _type: kube_cr_integration_instance_job
#      _class: Task
#      propertyToFieldMap:
#        _key: metadata.uid
#        name: metadata.name
#        namespace: metadata.namespace
#        createdOn: metadata.creationTimestamp
#        accountId: spec.accountId
#        certificateIdentity: spec.certificateIdentity
#        image: spec.image
#        integrationDefinitionName: spec.integrationDefinitionName
#        integrationInstanceId: spec.integrationInstanceId
#        integrationInstanceJobId: spec.integrationInstanceJobId
#        integrationRunnerName: spec.integrationRunnerName
#        secretName: spec.secretName
#
#  relationships:
#    - _class: HAS
#      sourceType: kube_cr_integration_runner
#      targetType: kube_secret
#      matchBy:
#        secretName: name
#        namespace: namespace
#    - _class: HAS
#      sourceType: kube_cr_integration_instance_job
#      targetType: kube_secret
#      matchBy:
#        secretName: name
#        namespace: namespace
#    - _class: HAS
#      sourceType: kube_cr_integration_instance_job
#      targetType: kube_cr_integration_runner
#      matchBy:
#        integrationRunnerName: name
#        namespace: namespace