apiVersion: integrations.jupiterone.io/v1
kind: IntegrationRunner
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  accountId: {{ .Values.accountID }}
  secretName: {{ .Release.Name }}-j1internal
  secretAPITokenName: {{ .Values.secretAPITokenName }}
  syncIntervalSeconds: {{ .Values.syncIntervalSeconds }}
  jupiterOneEnvironment: {{ .Values.jupiterOneEnvironment }}
