{{if .Values.createSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretAPITokenName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.apiToken | b64enc }}
{{- end }}