# The name of the secret that holds the API token.
# The key in the secret must be 'token'
secretAPITokenName: j1token

# Set this to false if you are using an external secret
createSecret: true

# This is an account level API token
# This is only required if 'createSecret' is true
apiToken: <api-token>

# The JupiterOne account ID, found in the JupiterOne UI under Settings > Account Management
accountID: <account-id>

# The interval in seconds for syncing data with JupiterOne
syncIntervalSeconds: 30

# The environment for JupiterOne API
jupiterOneEnvironment: us
