name: Pull Request Checks

on:
  pull_request:
    paths:
      - 'charts/jupiterone-integration-operator/**'
      - 'charts/jupiterone-integration-runner/**'

jobs:
  verify-operator-crds:
    name: Verify Operator CRDs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify GitHub CLI is available
        run: gh version

      - name: Verify CRDs are in sync
        run: make verify-crds
        env:
          GH_TOKEN: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
